In [ ]:
#Task1

In [1]:
while True: 
  x= int(input("Enter yout score"))
  if x >50 and x<100:
    print("Passed")
    break
  else:
    print("failed")

Enter yout score21
failed
Enter yout score50
failed
Enter yout score51
Passed

Taask2

In [18]:
sum = 0
neg_count = 0
prev_num = None

while True:
    num = int(input("Enter a number: "))
    if sum + num > 100:
        print("Sum of numbers exceeds 100")
        break

    if num < 0:
        neg_count += 1
        if neg_count > 10:
            print("More than 10 negative numbers entered")
            break

    if prev_num == num:
        print("Two consecutive numbers have the same value")
        break
 
    sum += num
    prev_num = num

print("End")

Enter a number: 30
Enter a number: 35
Enter a number: 37
Sum of numbers exceeds 100
End

Task3

In [19]:
alcohol_ml = float(input("Enter the amount of alcohol consumed in milliliters: "))
alcohol_percent = float(input("Enter the percentage of alcohol in the drink: "))
weight = float(input("Enter your weight in kilograms: "))
gender = input("Enter your gender (male or female): ")
alcohol_amount = alcohol_ml * alcohol_percent / 100 * 0.8 # 0.8 is the density of alcohol in g/ml
k = 0.7 if gender == 'male' else 0.6
bac = alcohol_amount / (k * weight)
print("Your blood alcohol content is {:.2f} per mille".format(bac))

Enter the amount of alcohol consumed in milliliters: 25
Enter the percentage of alcohol in the drink: 25
Enter your weight in kilograms: 25
Enter your gender (male or female):
Your blood alcohol content is 0.33 per mille

Task4

In [23]:
year = int(input("Enter the year between 1900 and 2099"))
a= year%19 
b= year%4
c= year%7
d =((a*19)+24)%30
e= (2*b + 4*c + 6*d + 5)%7
if d+e<10:
  print("day",d+e+22,"of March")
else:
  print(d+e-9,"of April")

Enter the year between 1900 and 20992022
17 of April